---
title: "Covid"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(roll)
library(magrittr)

# import data frames COVID: cases, tests and population size of municipalities
dc <- read_delim(here("exercises", "ws02", "covid", "Municipality_cases_time_series.csv"), ";", escape_double = FALSE, trim_ws = TRUE)
dt <- read_delim(here("exercises", "ws02", "covid", "Municipality_tested_persons_time_series.csv"), ";", escape_double = FALSE, trim_ws = TRUE)
dsize <- read_delim(here("exercises", "ws02", "covid", "Municipality_test_pos.csv"), ";", escape_double = FALSE, trim_ws = TRUE)

# make data tidy
dc %<>% 
  pivot_longer(cols = !date_sample, names_to = "kommune", values_to = "casesDiagnosed") %>% arrange(kommune, date_sample)

dt %<>% 
  pivot_longer(cols = !PrDate_adjusted, names_to = "kommune", values_to = "testsConducted") %>%
  arrange(kommune, PrDate_adjusted) %>%
  rename(date_sample = PrDate_adjusted)

# check there are no NA in the set
sum(is.na(dc$casesDiagnosed))
sum(is.na(dt$testsConducted))
sum(is.na(dt$testsConducted))
sum(is.na(dsize$Befolkningstal))

# make data compatible rename columns for merging and
dsize <- dsize %>%
  select(contains("Kom"), Befolkningstal) %>%
  rename("kID" = `Kommune_(id)`, "kommune" = `Kommune_(navn)`, population = Befolkningstal) %>%
  mutate(population = population * 1000) %>%
  select(-kID)

# check Kommune name can be used as key
dc[!(dc$kommune %in% dsize$kommune), ]$kommune
dsize[!(dsize$kommune %in% dt$kommune), ]$kommune
dt[!(dt$kommune %in% dsize$kommune), ]$kommune

# ooops!
# for some reason one data frame uses Københaven the other Copenhagen),
dsize$kommune <- str_replace(dsize$kommune, "København", "Copenhagen")

# check again keys are clean OK re-run rows 35-37

# merge data together
dc <- merge(dc, dsize)
dt <- merge(dt, dsize)

# create new variables (e.g. rolling aggregates)
dc %<>% 
  group_by(kommune) %>%
  mutate(casesDPer100k = casesDiagnosed / (population / 1000), 
         dcr7d = roll_sum(casesDiagnosed, width = 7, min_obs = 1), 
         ir7dP100k = dcr7d / (population / 1000))

dt %<>% 
  group_by(kommune) %>% 
  mutate(testsPer100k = testsConducted / (population / 1000), 
         tr7d = roll_sum(testsConducted, width = 7, min_obs = 1), 
         tr7dP100k = tr7d / (population / 1000))

# merge test with case data
df <- merge(dc, dt)

df$PosTestRate7d <- df$ir7dP100k / df$tr7dP100k

# check there were no diagnosis without tests
sum(df$casesDiagnosed > df$testsConducted)
```

## Covid data analysis DK overview


```{r cars}

```

## Including Plots



```{r}

```



